DROP TABLE IF EXISTS TB_USER;
 
CREATE TABLE TB_USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  balance INT NOT NULL
);

/**
CREATE TABLE IF NOT EXISTS TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

**/
